version: 2

updates:
- package-ecosystem: "cargo"
  directory: "/evaluator"
  schedule:
    interval: daily

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: "npm"
  directory: "/site"
  schedule:
    interval: "daily"
