[dependencies]
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.40.0" }
ws-tool = { version = "0.11.0", features = ["async"] }

[package]
edition = "2021"
name = "ws-tool"
publish = false
version = "0.0.0"
